# Generated by Django 3.1.2 on 2021-02-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210123_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_ranking',
            field=models.BooleanField(default=True),
        ),
    ]
